#!/usr/bin/env python3

# Usage: filter-csv exclude1.txt exclude2.txt < prober_syn_across_all_exp.csv > prober_syn_across_all_exp_filtered.csv

import csv
import getopt
import sys

REMOVE_FIELD_NAMES = set((
    "",
    "ip_dst",
    "tcp_dstport",
    "payload",
))

_, exclude_filenames = getopt.gnu_getopt(sys.argv[1:], "")

exclude = set()
for exclude_filename in exclude_filenames:
    with open(exclude_filename) as f:
        exclude.update(line.strip() for line in f)

def parse_bool(v):
    if v == "False":
        return False
    elif v == "True":
        return True
    else:
        raise ValueError(f"unknown boolean value {v!r}")

r = csv.DictReader(sys.stdin, delimiter = ";")
w = csv.DictWriter(sys.stdout, delimiter = ";", lineterminator="\n", fieldnames = [x for x in r.fieldnames if x not in REMOVE_FIELD_NAMES])
w.writeheader()

for row in r:
    for x in REMOVE_FIELD_NAMES:
        del row[x]
    if row["ip_src"] in exclude:
        continue

    w.writerow(row)
